# Generated by Django 4.2.3 on 2023-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="msid",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="team_name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
