version: '3.8'

services:
  web:
    build: ./backend
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=release
      - POSTGRES_PASSWORD=release
      - POSTGRES_DB=release_dev
volumes:
  postgres_data: