version: "3.8"

services:
  release-api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.prod
    image: achhabr9/release-api
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    restart: always
    expose:
      - 8000
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db
  release-ui:
    # build:
    #   context: ./frontend
    image: achhabr9/release-ui
    restart: always
    expose:
      - 3000
    env_file:
      - ./frontend/.env.production
    environment:
      NEXT_PUBLIC_API: http://rn000133847.uhc.com
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    restart: always
    ports:
      - 80:80
    depends_on:
      - release-ui
      - release-api

volumes:
  postgres_data:
  static_volume:
