# Generated by Django 4.2.3 on 2025-10-23 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="uuid",
            new_name="session_id",
        ),
    ]
