# Generated by Django 4.2.3 on 2023-07-24 08:47

from django.db import migrations, models
import django_enumfield.db.fields
import tickets.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "impact",
                    django_enumfield.db.fields.EnumField(
                        enum=tickets.models.Ticket.Importance
                    ),
                ),
                (
                    "priority",
                    django_enumfield.db.fields.EnumField(
                        enum=tickets.models.Ticket.Importance
                    ),
                ),
                ("assigned_to", models.CharField(max_length=64)),
                ("description", models.TextField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
