# Generated by Django 4.2.3 on 2023-09-08 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo", models.URLField(max_length=1024)),
                ("service", models.CharField(max_length=1024)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("repo", models.URLField(max_length=1024)),
                ("service", models.CharField(max_length=1024)),
                (
                    "release_branch",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                (
                    "hotfix_branch",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                ("special_notes", models.TextField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
