# Generated by Django 4.2.3 on 2023-09-12 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="release",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
