# Generated by Django 4.2.3 on 2023-09-14 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0002_release_name_alter_release_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="hotfix_branch",
        ),
        migrations.RemoveField(
            model_name="release",
            name="release_branch",
        ),
        migrations.RemoveField(
            model_name="release",
            name="repo",
        ),
        migrations.RemoveField(
            model_name="release",
            name="service",
        ),
        migrations.RemoveField(
            model_name="release",
            name="special_notes",
        ),
        migrations.RemoveField(
            model_name="release",
            name="tag",
        ),
        migrations.AlterField(
            model_name="release",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="ReleaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo", models.URLField(max_length=1024)),
                ("service", models.CharField(max_length=1024)),
                (
                    "release_branch",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                (
                    "hotfix_branch",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                ("special_notes", models.TextField(default=None, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
