# Generated by Django 4.2.3 on 2023-09-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0003_remove_release_hotfix_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constant",
            name="name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
