# Generated by Django 4.2.3 on 2023-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0005_approver"),
    ]

    operations = [
        migrations.AddField(
            model_name="approver",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
