# Generated by Django 4.2.3 on 2023-10-04 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0007_revokeapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="revokeapproval",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
