# Generated by Django 4.2.3 on 2023-10-04 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("releases", "0008_revokeapproval_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revokeapproval",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="revokeapproval",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoke_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
