# Generated by Django 4.2.3 on 2023-11-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0010_release_created_by_release_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="devops_notes",
            field=models.TextField(default=None, null=True),
        ),
    ]
