# Generated by Django 4.2.3 on 2023-11-03 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("releases", "0011_releaseitem_devops_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approver",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
