# Generated by Django 4.2.3 on 2023-12-08 07:39

from django.db import migrations
import django_enumfield.db.fields
import releases.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "releases",
            "0018_release_deployment_comment_release_deployment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="deployment_status",
            field=django_enumfield.db.fields.EnumField(
                blank=True,
                default=None,
                enum=releases.models.Release.DeploymentStatus,
                null=True,
            ),
        ),
    ]
