# Generated by Django 4.2.3 on 2023-12-08 10:55

from django.db import migrations
import django_enumfield.db.fields
import releases.models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0019_alter_release_deployment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="deployment_status",
            field=django_enumfield.db.fields.EnumField(
                default=0, enum=releases.models.Release.DeploymentStatus
            ),
        ),
    ]
