# Generated by Django 4.2.3 on 2023-12-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0021_alter_constant_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseitem",
            name="repo",
            field=models.CharField(max_length=1024),
        ),
    ]
