# Generated by Django 4.2.3 on 2024-04-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0022_alter_releaseitem_repo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalendReleaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_name", models.CharField(max_length=1024)),
                ("package_location", models.CharField(max_length=5120)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talend_items",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
