# Generated by Django 4.2.3 on 2024-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0023_talendreleaseitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releaseitem",
            name="hotfix_branch",
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="feature_number",
            field=models.CharField(
                blank=True, default=None, max_length=2048, null=True
            ),
        ),
    ]
