# Generated by Django 4.2.3 on 2024-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0024_remove_releaseitem_hotfix_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talendreleaseitem",
            name="feature_number",
            field=models.CharField(
                blank=True, default=None, max_length=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="talendreleaseitem",
            name="special_notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
