# Generated by Django 4.2.3 on 2024-06-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("releases", "0025_talendreleaseitem_feature_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="deployed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_deployed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="azure_env",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="azure_tenant",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
