# Generated by Django 4.2.3 on 2024-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0027_releaseitem_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseitem",
            name="job_status",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="releaseitem",
            name="queue_id",
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
