# Generated by Django 4.2.3 on 2024-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0028_releaseitem_job_status_releaseitem_queue_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseitem",
            name="queue_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
