# Generated by Django 4.2.3 on 2024-06-13 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "releases",
            "0030_releaseitem_job_logs_alter_releaseitem_devops_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="approver",
            name="approved_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="approver",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
